### ISSUE TITLE
Модули "Цитата из Библии"

### ISSUE THREAD

**Issue by tupikoff** [bobuk/hollybooks#4]
@bobuk есть много разных переводов Библии в виде модулей для программы "Цитата из Библии". Они, правда в html формате. Не настолько формализованное, как твои json, но всё же.
Можно либо их использовать, либо конвертировать.
http://bqt.ru/Katalog?v=13xs

p.s. если не секрет, для чего тебе Библия в json?)

**Comment by bobuk** [comment]
Привет. в формате HTML их можно скачать с любого сайта.

Я провожу разные эксперименты

**Comment by il-krylov** [comment]
A ТАНАХ не планируется?

**Comment by bobuk** [comment]
Я не планировал. Все же это фактически другая книга.
