### ISSUE TITLE
Некоторые файлы испорчены?

### ISSUE THREAD

**Issue by vovkkk** [bobuk/hollybooks#5]
Например, https://github.com/bobuk/holybooks/blob/master/RU/OT/1CH/NRP.json#L16 — id 3 повторяется 2 раза, id 4 — 3 раза, и т.д. Некоторые текстовые поля содержат только один пробел.

Если так и должно быть, то это не очевидно (в Синодальной версии все id «уникальные») — нужно указать в ридми.

**Comment by iilinegor** [comment]
Какой глубокий вопрос

**Comment by ghost** [comment]
Просто любопытно: с чем это может быть связано?
